plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/macbookdenoah/projet claude 2026/betwise/frontend/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/macbookdenoah/projet claude 2026/betwise/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]